[package]
name = "fullerene"
version = "0.1.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
